/**
 * Phase: emit — verify the agent has produced `reports.md` with required
 * sections. The agent writes the prose; this phase only gates on shape.
 *
 * Required sections: Overview, Brief / Spec / Tasks, QA, Code review,
 * Completion, CI / Follow-up. Final line must declare
 * `Status: COMPLETE` or `Status: PARTIAL` (PARTIAL = some artifacts blocked).
 */

'use strict';

const fs = require('node:fs');
const path = require('node:path');

const { REPORTS_PHASES } = require('../../reports-phase-registry');

const REPORT_FILE = 'reports.md';
const LEARNINGS_FILE = 'learnings.md';
// GH-318: single shape gate for the optional learnings companion — the
// `# Learnings` heading followed by the five sections in order. Pure
// observability output: a missing/malformed file only warns, never blocks.
const LEARNINGS_SHAPE_RE =
  /^#\s+Learnings\b[\s\S]*?^##\s+Decisions\b[\s\S]*?^##\s+Lessons Learned\b[\s\S]*?^##\s+Patterns Discovered\b[\s\S]*?^##\s+Surprises\b[\s\S]*?^##\s+Metrics\b/m;
const REQUIRED_SECTIONS = [
  /^##\s+Overview\b/im,
  /^##\s+Brief\s*\/\s*Spec\s*\/\s*Tasks\b/im,
  /^##\s+QA\b/im,
  /^##\s+Code review\b/im,
  /^##\s+Completion\b/im,
  /^##\s+CI\s*\/\s*Follow-up\b/im,
];
const STATUS_RE = /^Status:\s*(COMPLETE|PARTIAL)\b/im;

// GH-318: non-blocking learnings.md check. Returns { present, warning }.
function checkLearnings(tasksDir) {
  const p = path.join(tasksDir, LEARNINGS_FILE);
  if (!fs.existsSync(p)) {
    return {
      present: false,
      warning: `\`${LEARNINGS_FILE}\` not found — optional, but recommended (GH-318).`,
    };
  }
  let text;
  try {
    text = fs.readFileSync(p, 'utf8');
  } catch (e) {
    return { present: true, warning: `could not read \`${LEARNINGS_FILE}\`: ${e.message}` };
  }
  if (!LEARNINGS_SHAPE_RE.test(text)) {
    return {
      present: true,
      warning: `\`${LEARNINGS_FILE}\` malformed — expected \`# Learnings\` then \`## Decisions\`, \`## Lessons Learned\`, \`## Patterns Discovered\`, \`## Surprises\`, \`## Metrics\` (in order). Non-blocking.`,
    };
  }
  return { present: true, warning: null };
}

function validate(ctx) {
  const p = path.join(ctx.tasksDir, REPORT_FILE);
  if (!fs.existsSync(p)) {
    return {
      ok: false,
      errors: [
        `\`${REPORT_FILE}\` missing. Author the cross-step summary using \`reports-summary.json\`.`,
      ],
    };
  }
  let text;
  try {
    text = fs.readFileSync(p, 'utf8');
  } catch (e) {
    return { ok: false, errors: [`could not read \`${REPORT_FILE}\`: ${e.message}`] };
  }
  const missing = [];
  const names = [
    '## Overview',
    '## Brief / Spec / Tasks',
    '## QA',
    '## Code review',
    '## Completion',
    '## CI / Follow-up',
  ];
  REQUIRED_SECTIONS.forEach((re, i) => {
    if (!re.test(text)) missing.push(names[i]);
  });
  if (missing.length) {
    return { ok: false, errors: [`\`${REPORT_FILE}\` missing section(s): ${missing.join(', ')}.`] };
  }
  if (!STATUS_RE.test(text)) {
    return {
      ok: false,
      errors: [`\`${REPORT_FILE}\` missing final \`Status: COMPLETE\` or \`Status: PARTIAL\`.`],
    };
  }
  const learnings = checkLearnings(ctx.tasksDir);
  return {
    ok: true,
    warnings: learnings.warning ? [learnings.warning] : [],
    summary:
      learnings.present && !learnings.warning
        ? 'reports.md + learnings.md complete'
        : 'reports.md complete',
  };
}

function instructions(ctx) {
  return [
    '# reports-next — Phase 4 of 6: EMIT',
    `Ticket: ${ctx.ticket}`,
    '',
    'Write `reports.md` with:',
    '  ## Overview',
    '  ## Brief / Spec / Tasks',
    '  ## QA',
    '  ## Code review',
    '  ## Completion',
    '  ## CI / Follow-up',
    '  Status: COMPLETE | Status: PARTIAL',
    '',
    'Source: `reports-summary.json` (auto-generated by summarize phase).',
    '',
    'Also write `learnings.md` (GH-318 — recommended, never blocks):',
    '  # Learnings — <TICKET>',
    '  ## Decisions',
    '  ## Lessons Learned',
    '  ## Patterns Discovered',
    '  ## Surprises',
    '  ## Metrics',
    '',
    'Sources: brief/spec/tasks, *.check.md, `review-accountability.json`,',
    'follow-up-pr state, git diff stats. Non-obvious findings only.',
    '',
  ].join('\n');
}

module.exports = function register(registerPhase) {
  registerPhase(REPORTS_PHASES.emit, {
    next: REPORTS_PHASES.memorize,
    validate,
    instructions,
  });
};

module.exports.validate = validate;
module.exports.instructions = instructions;
module.exports.REPORT_FILE = REPORT_FILE;
module.exports.STATUS_RE = STATUS_RE;
module.exports.LEARNINGS_FILE = LEARNINGS_FILE;
module.exports.LEARNINGS_SHAPE_RE = LEARNINGS_SHAPE_RE;
module.exports.checkLearnings = checkLearnings;
