/**
 * report-cycle.js — check report folder lifecycle (extracted from
 * hooks/check-setup.js, which re-exports the public pieces).
 *
 * Owns the cycle marker, the purge guard and the folder setup. Lifted out
 * verbatim: check-setup.js had grown past the 400-line gate, and this is the
 * self-contained half — it touches only the report folder, never git, config
 * or the ticket id.
 */

'use strict';

const fs = require('fs');
const path = require('path');

// ─── Check-cycle marker (GH-611 purge-race guard) ───────────────────────────
// setup runs on EVERY orchestrator pass (auto-advance hook + manual driving,
// possibly concurrently). Purging *.check.md unconditionally wiped reports
// that phase-1 agents had just written mid-cycle. The marker keys the purge
// to the changes hash: purge ONLY when a genuinely NEW cycle starts (no
// marker, or the hash changed), never while a cycle for the same hash is
// already in progress.

function cycleMarkerPath(reportFolder) {
  return path.join(reportFolder, '.check-cycle.json');
}

/**
 * True when old reports should be purged: no cycle marker yet, or the marker
 * records a different changes hash (previous cycle's reports are stale).
 */
function shouldPurgeReports(reportFolder, changesHash) {
  try {
    const marker = JSON.parse(fs.readFileSync(cycleMarkerPath(reportFolder), 'utf8'));
    return marker.changesHash !== changesHash;
  } catch {
    return true; // no/unreadable marker → new cycle
  }
}

// Atomic tmp + rename marker write so concurrent readers never see a partial file.
function writeCycleMarker(reportFolder, changesHash) {
  const target = cycleMarkerPath(reportFolder);
  const tmp = `${target}.${process.pid}.tmp`;
  fs.writeFileSync(tmp, JSON.stringify({ changesHash, startedAt: new Date().toISOString() }));
  fs.renameSync(tmp, target);
}

/** Delete old screenshots and *.check.md / README.md report files. */
function purgeOldReports(reportFolder, screenshotsFolder) {
  // Clean old screenshots
  if (fs.existsSync(screenshotsFolder)) {
    for (const file of fs.readdirSync(screenshotsFolder)) {
      if (/\.(png|jpg|jpeg)$/i.test(file)) {
        fs.unlinkSync(path.join(screenshotsFolder, file));
      }
    }
  }
  // Clean old report files (only *.check.md and README.md generated by /check command)
  // This preserves implement.md and other non-check files
  for (const file of fs.readdirSync(reportFolder)) {
    if (file.endsWith('.check.md') || file === 'README.md') {
      fs.unlinkSync(path.join(reportFolder, file));
    }
  }
}

/**
 * Create report folders and clean old files.
 *
 * The purge is (a) keyed on the changes hash via the cycle marker — an
 * in-progress cycle is never purged — and (b) serialized behind an O_EXCL
 * lockfile so two concurrent setup invocations can't both decide to purge.
 *
 * @returns {boolean} true when old reports were purged (new cycle started)
 */
function setupReportFolder(reportFolder, changesHash) {
  const screenshotsFolder = path.join(reportFolder, 'screenshots');

  // Create folders
  fs.mkdirSync(screenshotsFolder, { recursive: true });

  if (!shouldPurgeReports(reportFolder, changesHash)) {
    return false; // cycle for this hash already in progress — keep reports
  }

  // Serialize the purge: if another setup holds the lock, skip — it is
  // already handling this cycle's purge + marker.
  const lockPath = path.join(reportFolder, '.check-cycle.lock');
  let fd;
  try {
    fd = fs.openSync(lockPath, 'wx');
  } catch {
    return false; // concurrent setup owns the purge
  }
  try {
    fs.writeSync(fd, String(process.pid));
    // Re-check under the lock (another setup may have just written the marker)
    if (!shouldPurgeReports(reportFolder, changesHash)) return false;
    purgeOldReports(reportFolder, screenshotsFolder);
    writeCycleMarker(reportFolder, changesHash);
    return true;
  } finally {
    fs.closeSync(fd);
    try {
      fs.unlinkSync(lockPath);
    } catch {
      /* best-effort */
    }
  }
}

module.exports = {
  cycleMarkerPath,
  shouldPurgeReports,
  writeCycleMarker,
  purgeOldReports,
  setupReportFolder,
};
