#!/usr/bin/env node
/**
 * /check Setup Script
 *
 * Handles:
 * - Determining worktree path and report folder
 * - Generating CHANGES_HASH from git diff
 * - Checking if reports are up-to-date (cache validation)
 * - Creating folders and cleaning old files
 * - Analyzing impacted apps
 *
 * Usage: node check-setup.js [TICKET_ID]
 *
 * Output: JSON object with setup variables
 */

const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');
const config = require(path.join(__dirname, '..', '..', 'lib', 'config'));

/**
 * Resolve ticket ID from CLI args and environment.
 * Precedence: CLI arg > TICKET_ID env > JIRA_TICKET_ID env (backward compat)
 * See hooks/__tests__/check-setup-ticket-id.test.js for coverage.
 */
function resolveTicketId(argv = [], env = {}) {
  return argv[0] || env.TICKET_ID || env.JIRA_TICKET_ID || '';
}

const TICKET_ID = resolveTicketId(process.argv.slice(2), process.env);

// Shared shell helper (also used by lib/impacted-apps.js)
const { exec } = require(path.join(__dirname, '..', 'lib', 'exec-util'));

// Use centralized getBaseBranch() from config
const getBaseBranch = config.getBaseBranch;

/**
 * Get the main worktree path
 */
function getMainWorktreePath() {
  const output = exec('git worktree list');
  const firstLine = output.split('\n')[0];
  return firstLine.split(/\s+/)[0];
}

/**
 * Get current branch name
 */
function getBranchName() {
  return exec('git branch --show-current');
}

/**
 * Generate hash from changed file contents
 * Same changes = same hash, any line change = different hash
 * Uses -w to ignore whitespace-only changes
 */
function generateChangesHash() {
  // Use -w to ignore whitespace changes (prevents false cache misses)
  const baseBranch = getBaseBranch();
  const diff = exec(`git diff ${baseBranch}...HEAD -w`);
  if (!diff) {
    // No changes, use empty hash
    return 'no-changes';
  }

  // Use Node's crypto for hashing
  const crypto = require('crypto');
  const hash = crypto.createHash('sha256').update(diff).digest('hex');
  return hash.substring(0, 12);
}

/**
 * Check if reports are up-to-date by comparing hashes
 */
function checkReportsCache(reportFolder, currentHash) {
  const readmePath = path.join(reportFolder, 'README.md');

  if (!fs.existsSync(readmePath)) {
    return { cached: false, reason: 'No README.md found' };
  }

  const content = fs.readFileSync(readmePath, 'utf8');
  const match = content.match(/\*\*Changes Hash:\*\*\s*([a-f0-9]{12}|no-changes)/);

  if (!match) {
    return { cached: false, reason: 'No hash found in README.md' };
  }

  const cachedHash = match[1];

  if (cachedHash === currentHash) {
    return {
      cached: true,
      cachedHash,
      readme: content,
    };
  }

  return {
    cached: false,
    reason: 'Hash mismatch',
    previousHash: cachedHash,
    currentHash,
  };
}

// ─── Check-cycle marker (GH-611 purge-race guard) ───────────────────────────
// setup runs on EVERY orchestrator pass (auto-advance hook + manual driving,
// possibly concurrently). Purging *.check.md unconditionally wiped reports
// that phase-1 agents had just written mid-cycle. The marker keys the purge
// to the changes hash: purge ONLY when a genuinely NEW cycle starts (no
// marker, or the hash changed), never while a cycle for the same hash is
// already in progress.

function cycleMarkerPath(reportFolder) {
  return path.join(reportFolder, '.check-cycle.json');
}

/**
 * True when old reports should be purged: no cycle marker yet, or the marker
 * records a different changes hash (previous cycle's reports are stale).
 */
function shouldPurgeReports(reportFolder, changesHash) {
  try {
    const marker = JSON.parse(fs.readFileSync(cycleMarkerPath(reportFolder), 'utf8'));
    return marker.changesHash !== changesHash;
  } catch {
    return true; // no/unreadable marker → new cycle
  }
}

// Atomic tmp + rename marker write so concurrent readers never see a partial file.
function writeCycleMarker(reportFolder, changesHash) {
  const target = cycleMarkerPath(reportFolder);
  const tmp = `${target}.${process.pid}.tmp`;
  fs.writeFileSync(tmp, JSON.stringify({ changesHash, startedAt: new Date().toISOString() }));
  fs.renameSync(tmp, target);
}

/** Delete old screenshots and *.check.md / README.md report files. */
function purgeOldReports(reportFolder, screenshotsFolder) {
  // Clean old screenshots
  if (fs.existsSync(screenshotsFolder)) {
    for (const file of fs.readdirSync(screenshotsFolder)) {
      if (/\.(png|jpg|jpeg)$/i.test(file)) {
        fs.unlinkSync(path.join(screenshotsFolder, file));
      }
    }
  }
  // Clean old report files (only *.check.md and README.md generated by /check command)
  // This preserves implement.md and other non-check files
  for (const file of fs.readdirSync(reportFolder)) {
    if (file.endsWith('.check.md') || file === 'README.md') {
      fs.unlinkSync(path.join(reportFolder, file));
    }
  }
}

/**
 * Create report folders and clean old files.
 *
 * The purge is (a) keyed on the changes hash via the cycle marker — an
 * in-progress cycle is never purged — and (b) serialized behind an O_EXCL
 * lockfile so two concurrent setup invocations can't both decide to purge.
 *
 * @returns {boolean} true when old reports were purged (new cycle started)
 */
function setupReportFolder(reportFolder, changesHash) {
  const screenshotsFolder = path.join(reportFolder, 'screenshots');

  // Create folders
  fs.mkdirSync(screenshotsFolder, { recursive: true });

  if (!shouldPurgeReports(reportFolder, changesHash)) {
    return false; // cycle for this hash already in progress — keep reports
  }

  // Serialize the purge: if another setup holds the lock, skip — it is
  // already handling this cycle's purge + marker.
  const lockPath = path.join(reportFolder, '.check-cycle.lock');
  let fd;
  try {
    fd = fs.openSync(lockPath, 'wx');
  } catch {
    return false; // concurrent setup owns the purge
  }
  try {
    fs.writeSync(fd, String(process.pid));
    // Re-check under the lock (another setup may have just written the marker)
    if (!shouldPurgeReports(reportFolder, changesHash)) return false;
    purgeOldReports(reportFolder, screenshotsFolder);
    writeCycleMarker(reportFolder, changesHash);
    return true;
  } finally {
    fs.closeSync(fd);
    try {
      fs.unlinkSync(lockPath);
    } catch {
      /* best-effort */
    }
  }
}

// Impacted-app / affected-file analysis lives in ../lib/impacted-apps.js
const { getImpactedApps, getAffectedFiles } = require(
  path.join(__dirname, '..', 'lib', 'impacted-apps')
);

// Docs loading (READ_DOCS_ON_*) lives in ../lib/load-docs.js
const { loadDocsFromPaths, DOCS_DENYLIST } = require(
  path.join(__dirname, '..', 'lib', 'load-docs')
);

/**
 * Derive taskId from TICKET_ID or branch name fallback.
 * When TICKET_ID is provided (from orchestrator), use as-is — it may contain
 * a suffix like GH-181/phase1 which creates a subdirectory (intended behavior).
 * Only sanitize the branch name fallback: strip unsafe chars to avoid path issues.
 */
function deriveTaskId(ticketId, branchName) {
  if (ticketId) {
    // Validate: reject absolute paths, path traversal, and unsafe characters.
    // Allow one optional suffix segment (e.g., GH-181/phase1) with safe chars.
    if (path.isAbsolute(ticketId)) return branchName.replace(/[^a-zA-Z0-9._-]/g, '-');
    if (/\.\./.test(ticketId)) return branchName.replace(/[^a-zA-Z0-9._-]/g, '-');
    // Allow: alphanumeric, hyphens, underscores, dots, and one / for suffix
    if (!/^[a-zA-Z0-9._-]+(\/[a-zA-Z0-9._-]+)?$/.test(ticketId)) {
      return branchName.replace(/[^a-zA-Z0-9._-]/g, '-');
    }
    return ticketId;
  }
  return branchName.replace(/[^a-zA-Z0-9._-]/g, '-');
}

/**
 * Main execution
 */
function main() {
  const mainWorktreePath = getMainWorktreePath();
  const branchName = getBranchName();

  // Determine report folder - use parent of main worktree + tasks
  const taskId = deriveTaskId(TICKET_ID, branchName);
  const reportFolder = path.join(mainWorktreePath, '..', 'tasks', taskId);

  // Generate changes hash
  const changesHash = generateChangesHash();

  // Check cache
  const cacheResult = checkReportsCache(reportFolder, changesHash);

  // Get impacted apps
  const impactedApps = getImpactedApps();

  // Get affected files for QA dependency tracing
  const affectedFiles = getAffectedFiles();

  // Load project-specific docs for each agent type (always include all keys for stable schema)
  // Use current worktree root (not mainWorktreePath) so docs reflect the feature branch
  const currentRepoRoot = exec('git rev-parse --show-toplevel') || process.cwd();
  const docVars = [
    'READ_DOCS_ON_REVIEW',
    'READ_DOCS_ON_QA',
    'READ_DOCS_ON_DEV',
    'READ_DOCS_ON_E2E',
    'READ_DOCS_ON_TEST',
    'READ_DOCS_ON_STORYBOOK',
    'READ_DOCS_ON_PR',
  ];
  const loadedDocs = {};
  for (const varName of docVars) {
    const key = varName.replace('READ_DOCS_ON_', '').toLowerCase() + 'Docs';
    loadedDocs[key] = loadDocsFromPaths(varName, config[varName], currentRepoRoot);
  }

  // Output result
  const result = {
    mainWorktreePath,
    branchName,
    ticketId: taskId,
    jiraTicketId: taskId, // deprecated: use ticketId instead
    reportFolder,
    changesHash,
    cache: cacheResult,
    impactedApps,
    affectedFiles,
    screenshotsFolder: path.join(reportFolder, 'screenshots'),
  };

  // Always include all doc keys for stable JSON schema
  result.reviewDocs = loadedDocs.reviewDocs;
  result.qaDocs = loadedDocs.qaDocs;
  result.devDocs = loadedDocs.devDocs;
  result.e2eDocs = loadedDocs.e2eDocs;
  result.testDocs = loadedDocs.testDocs;
  result.storybookDocs = loadedDocs.storybookDocs;
  result.prDocs = loadedDocs.prDocs;

  // If not cached, setup the folder (purge is guarded by the cycle marker —
  // it only fires when a genuinely new cycle starts, see setupReportFolder)
  if (!cacheResult.cached) {
    result.reportsPurged = setupReportFolder(reportFolder, changesHash);
    result.foldersCreated = true;
  }

  console.log(JSON.stringify(result, null, 2));

  // Exit with code 0 if cached (skip checks), 1 if not cached (run checks)
  // Actually, let's not use exit codes - just output the JSON
  // The calling code will check result.cache.cached
}

// Allow importing individual functions for testing
if (require.main === module) {
  main();
} else {
  module.exports = {
    loadDocsFromPaths,
    DOCS_DENYLIST,
    resolveTicketId,
    deriveTaskId,
    setupReportFolder,
    shouldPurgeReports,
  };
}
